services:
  openfire:
    image: openfire:${OPENFIRE_VERSION}
    ports:
      - "9090:9090/tcp"
      - "9091:9091/tcp"
      - "5222:5222/tcp"
      - "7777:7777/tcp"
    volumes:
      - ./config/docker/openfire/data:/var/lib/openfire
      - ./config/docker/openfire/logs:/var/log/openfire
